In [4]:
import requests
import bs4
from bs4 import BeautifulSoup
import pandas as pd

In [6]:
books = pd.read_csv('books.csv')

In [7]:
books.head()

,ISBN,Book-Title,Price,Year-Of-Publication,Publisher ID
0,0195153448,Classical Mythology,75,2002,1
1,0198320264,Julius Caesar (Oxford School Shakespeare),20,2001,1
2,0192815318,Cranford (The World's Classics),25,1982,1
3,0198604025,How Not to Say What You Mean: A Dictionary of ...,80,2003,1
4,0002005018,Clara Callan,30,2001,2

In [9]:
books.shape

(892, 5)

In [8]:
books.ISBN.nunique()

892

In [12]:
isbn_list = books.ISBN.unique()

In [13]:
def get_html(ISBN):
    URL = f"https://www.goodreads.com/search?q={ISBN}"
    r = requests.get(URL)  
    html_soup = BeautifulSoup(r.content, 'html.parser') 
    return html_soup

In [83]:
count = 1
desc_dict = {isbn: '' for isbn in isbn_list}
for isbn in isbn_list:
    desc_div = None
    trial = 5
    while not desc_div and trial > 0:
        trial -= 1
        html = get_html(isbn)
        desc_div = html.find('div', {'id': 'description'})        
    if desc_div:
        if desc_div.find_all(attrs={"style" : "display:none"}):
            print(count)
            print(isbn)
            desc_dict[isbn] = desc_div.find_all(attrs={"style" : "display:none"})[0].text
            count += 1

1
0195153448
2
0192815318
3
0198604025
4
0002005018
5
0374157065
6
0374386676
7
0393045218
8
0393318435
9
0399135782
10
0399137807
11
039914370X
12
0425176428
13
0425163091
14
0425182908
15
042518630X
16
042511774X
17
0425184226
18
0425120279
19
0425098109
20
0425156842
21
0425178242
22
0425181111
23
042517736X
24
0425179672
25
0425174484
26
0425169626
27
0425184129
28
0425142485
29
0425049981
30
0425161722
31
0425134350
32
0425166619
33
0671870432
34
0679425608
35
0394743741
36
0375509038
37
0679429220
38
0375500766
39
0679427430
40
0679442790
41
039457513X
42
074322678X
43
0684848783
44
0684193957
45
0684177730
46
0684824442
47
068484267X
48
0684801221
49
0743230051
50
0743211383
51
0771074670
52
080652121X
53
0887841740
54
1558746218
55
155874262X
56
1567407781
57
1575663937
58
0440234743
59
0440223571
60
0440225701
61
0440222303
62
0440241413
63
0440235502
64
0440122090
65
0440117291
66
0440211727
67
0452264464
68
0609804618
69
0812923278
70
1841721522
71
0590629719
72
0590419625
73
0590687301
74
0439042917
75
043922165X
76
0439221684
77
0590514776
78
0689821166
79
0671021745
80
0020437501
81
0689832877
82
0689829698
83
068983585X
84
068983571X
85
0345402871
86
0345417623
87
0449005615
88
0345260317
89
0345465083
90
0345372700
91
0345311396
92
0345378490
93
0345404793
94
0345433173
95
0449006522
96
0449911004
97
0804111359
98
0345391691
99
0345430476
100
0449912302
101
0449005410
102
0345313097
103
0345424719
104
0449907481
105
0345441133
106
0345313860
107
0345369947
108
0345353625
109
0345379454
110
0345251733
111
0449911683
112
0345428900
113
0345395379
114
0345403339
115
0345429176
116
0345418778
117
0345391802
118
0449006557
119
0345404777
120
3404921038
121
3404121686
122
3404118960
123
0375406328
124
0679423079
125
0679450432
126
0394574745
127
0446310786
128
0060168013
129
0060177586
130
006015781X
131
038078243X
132
0380778556
133
0380717018
134
0380718332
135
0380807866
136
0380728729
137
0380728273
138
0380704587
139
0380792664
140
0380732688
141
0060558865
142
0380002450
143
0380817144
144
055321215X
145
055329198X
146
0553569058
147
0553210092
148
0553258524
149
0553802488
150
0553285343
151
0553107305
152
0553564528
153
055356451X
154
0553578693
155
0553101439
156
0553212583
157
0061099325
158
006102063X
159
006101351X
160
0380732335
161
0061000280
162
0061009059
163
0061042943
164
0553582747
165
0553584383
166
0553583468
167
0553280589
168
055358099X
169
0553289063
170
0553272837
171
0553225987
172
0553576925
173
0553579673
174
0553574167
175
0671888587
176
0671623249
177
0743439740
178
0671042858
179
0671004573
180
0671461494
181
0671023616
182
0671027387
183
0671018930
184
067153484X
185
067103619X
186
0671867113
187
0671021001
188
0671002481
189
0743424425
190
0671000306
191
0671673688
192
0743412621
193
0671868713
194
067170124X
195
0671525832
196
2266084372
197
2266029460
198
0671694049
199
0671742566
200
0671779338
201
0812523873
202
0812541642
203
0812519655
204
0812524853
205
0812521129
206
0812521331
207
0765341972
208
0842336214
209
0060914068
210
0060199563
211
006017143X
212
0060192631
213
0156047624
214
0156027321
215
0156013967
216
015600710X
217
0679810307
218
0679865691
219
0394895894
220
0440226694
221
0804106304
222
1853262404
223
1853260053
224
1853260673
225
1853260622
226
0312970242
227
0312252617
228
0312261594
229
0312953453
230
0312148267
231
0312963009
232
0312995423
233
0312278586
234
0060938412
235
038076654X
236
0380820447
237
0140067477
238
0140250964
239
0142001740
240
014023828X
241
0140286276
242
0140293248
243
0142000205
244
0140107649
245
0451625889
246
0451166892
247
0451208080
248
0451205197
249
0451525221
250
0451206673
251
0451162072
252
0451186648
253
0451203046
254
0451523318
255
0451202341
256
0451195663
257
0451184718
258
0451197275
259
0451176812
260
0451181379
261
0451205421
262
0451155750
263
0451204050
264
0451188209
265
0451185277
266
0441783589
267
087113375X
268
0871138646
269
0340767936
270
0060930365
271
0060929790
272
0060976845
273
0060977493
274
0060809027
275
0380730448
276
0060977477
277
0380815923
278
0060973897
279
0060932759
280
0060923245
281
0060913509
282
0688169678
283
0060938455
284
0060930187
285
0060930705
286
0060927240
287
0060934719
288
0553062042
289
0553202294
290
0316769487
291
0316602906
292
0316693006
293
0316782505
294
0316666343
295
0316735027
296
0316789089
297
0316969443
298
0316693200
299
8445071408
300
8445071769
301
3257233051
302
8484509141
303
0316748641
304
0316973742
305
0316735736
306
0316168815
307
0316776963
308
0385508042
309
0385416342
310
038542471X
311
0385490992
312
0385424728
313
0385472951
314
0385420161
315
0385493800
316
0446677450
317
0446608653
318
0446612545
319
0446612618
320
0446601640
321
044651747X
322
0446527165
323
0446610399
324
0446606197
325
0446610178
326
0446394521
327
0446364193
328
0446519138
329
0446523992
330
0446672211
331
0446525502
332
0446523569
333
0446527793
334
0446531332
335
0446300101
336
044661162X
337
0446364762
338
0671621009
339
0684822733
340
0743222229
341
067976397X
342
0375705856
343
0679751343
344
0679777431
345
0786863986
346
0786868015
347
8472238822
348
0671864769
349
0671027360
350
0743470389
351
0380619458
352
0380617625
353
0380710218
354
0061096091
355
0380538504
356
0446325805
357
0445402040
358
0786889160
359
0451410556
360
0743249992
361
0684717255
362
0840734530
363
9724119378
364
0330484516
365
038572179X
366
140003180X
367
0385418493
368
0385721420
369
038549825X
370
0393020371
371
0393321576
372
1900850303
373
1903019699
374
0345425294
375
0449207544
376
0449213773
377
0449212084
378
0449211770
379
0345369068
380
0449207757
381
0449245691
382
0449207595
383
0449131548
384
0449001954
385
8420639133
386
8476409419
387
0385336772
388
0385337639
389
0385335679
390
038533334X
391
0440949424
392
0440219078
393
0140252800
394
0140620664
395
0140620427
396
0451452755
397
0451456548
398
0451454243
399
0812575482
400
0060804157
401
039575514X
402
0618231617
403
0395877563
404
0486284735
405
0486282112
406
0486281965
407
0486292940
408
0486272664
409
0486272745
410
0830714014
411
0345354931
412
034543191X
413
0345335465
414
0345416848
415
0345370740
416
0345356578
417
0345428544
418
0553278223
419
3150000335
420
3257208669
421
3257210450
422
3257212054
423
3257212429
424
3257208626
425
2253005274
426
207053880X
427
3423241489
428
3426605686
429
3453212150
430
3462021095
431
3492045642
432
3492207006
433
3498020862
434
3499110695
435
3499151502
436
3518111000
437
3548254268
438
3570300099
439
3596292646
440
0385316895
441
0385314019
442
0385497466
443
0385509456
444
0385511612
445
0385504209
446
0385505833
447
0385730586
448
0440234964
449
0440218535
450
0440222818
451
0446605484
452
0452282152
453
0452283914
454
0452279690
455
0452277337
456
0515128554
457
0515118656
458
0515127833
459
0515134279
460
0515134368
461
0743486226
462
0743406176
463
0671042556
464
0803251718
465
0803233019
466
0804117934
467
080411952X
468
0060987103
469
0151008116
470
0156528207
471
0151001006
472
0375704965
473
0375719180
474
0679725393
475
0375726403
476
0679767789
477
0525947647
478
0525943862
479
052594463X
480
0060013117
481
0061040967
482
0060173289
483
0688180639
484
0060191929
485
0064407667
486
006052779X
487
0060563079
488
0061050474
489
0061052515
490
0064472264
491
0312156960
492
0312283784
493
0312890044
494
0375751513
495
0679603352
496
0375801677
497
0375814248
498
0375823352
499
037582345X
500
0375823468
501
0679893105
502
0380973839
503
0380973545
504
0394586239
505
0517577402
506
039456894X
507
0375403582
508
0679401377
509
0679450440
510
0394551427
511
0375501347
512
0394559487
513
0439510112
514
0451523415
515
0451527747
516
0451526341
517
0571197639
518
0670035262
519
0684833395
520
0684854953
521
0743229878
522
0743206053
523
0743206045
524
0684864843
525
0684868911
526
0684864320
527
0743213831
528
0749748001
529
0749748028
530
0963094424
531
1401201172
532
1563892278
533
1563898586
534
1563899388
535
156971620X
536
0374270325
537
0374343381
538
044023722X
539
0440224675
540
0440235057
541
0440225078
542
1573225487
543
1573228737
544
1573229148
545
1573229571
546
0520011171
547
0553278746
548
0553562819
549
0553574175
550
0553574159
551
0670855758
552
0670892963
553
0670031046
554
0872200760

555
0671649949
556
0743444167
557
0590406019
558
0064470113
559
0061064505
560
0553571486
561
0345435869
562
0345413369
563
0345339711
564
0345346971
565
038081840X
566
0060575808
567
0312988699
568
0312980388
569
0312995431
570
0385313748
571
0385337132
572
0385335407
573
0385306032
574
9681500555
575
0380711109
576
1559703237
577
3596214629
578
0671847546
579
0140374248
580
0140185216
581
0743411269
582
0767905938
583
0767903579
584
0767903285
585
0849953014
586
0891091963
587
0915811537
588
0802114369
589
1880185008
590
1567184294
591
156718796X
592
1862047626
593
0373484100
594
0373245696
595
0140104682
596
0140029400
597
0140021566
598
0449002632
599
0940322978
600
1579651658
601
1878424319
602
8440616252
603
8478097732
604
8478884963
605
0385333404
606
044021145X
607
0590947257
608
074345829X
609
0743458303
610
0786913878
611
0866119531
612
1561561428
613
0688163726
614
0380709260
615
0064409457
616
1569471096
617
0375414746
618
0394578791
619
0965404560
620
0805063897
621
0385495145
622
0385496907
623
0618119760
624
0618173870
625
0312195516
626
039914739X
627
0399147012
628
0399147128
629
051762639X
630
081296666X
631
1877727083
632
8845229041
633
887641486X
634
0140370900
635
0030096189
636
080521061X
637
0823032612
638
0679310002
639
0312288115
640
0316171107
641
0316116025
642
0743418190
643
0312145543
644
0312906552
645
080213825X
646
0849943728
647
0849943450
648
084994371X
649
0805056491
650
0816152446
651
0821772953
652
0821775863
653
0821770209
654
0440441501
655
0439061644
656
0439569842
657
0307118703
658
193072229X
659
0312986769
660
0312977905
661
0590021117
662
0807565288
663
0767908473
664
0399144463
665
0312206763
666
0811203220
667
0062507249
668
0062517856
669
1576737357
670
0807070718
671
0061080519
672
193156146X
673
225300670X
674
2253148539
675
2253043974
676
2253063339
677
2070362388
678
2253007102
679
2070417743
680
2070334368
681
2290314951
682
229000510X
683
0609605925
684
0380978539
685
0679410430
686
0609606727
687
1570717257
688
039304016X
689
0718144538
690
0007100221
691
0747549923
692
0140253580
693
0947782141
694
057120354X
695
0571209521
696
0349101779
697
185479549X
698
2871290911
699
1860198597
700
156341029X
701
1563410443
702
1563411148
703
1888451084
704
0451450256
705
1555835953
706
1555834531
707
0889740828
708
0553579681
709
0679801146
710
0440415993
711
038529929X
712
0517201658
713
0590897985
714
0152162577
715
015216250X
716
1562477528
717
0439221714
718
0439221706
719
185424597X
720
0753804700
721
0786890436
722
0521427150
723
080901582X
724
0373871562
725
0880701102
726
0688048730
727
0385479689
728
0440224829
729
0892967994
730
0061076031

In [137]:
isbn_l = []
desc_l = []
for isbn in desc_dict:  
    isbn_l.append(isbn)
    desc_l.append(desc_dict[isbn])

In [138]:
desc_df = pd.DataFrame()
desc_df['isbn'] = isbn_l
desc_df['desc'] = desc_l

In [145]:
desc_df.head()

         isbn                                               desc
0  0195153448  Featuring the authors' extensive, clear, and f...
1  0198320264  The Oxford School Shakespeare has become the p...
2  0192815318  `Cranford is in possession of the Amazons; all...
3  0198604025  We often use euphemisms when dealing with tabo...
4  0002005018  In a small town in Canada, Clara Callan reluct...

In [142]:
remaining_isbn = desc_df[desc_df['desc'] == ''].isbn.values

In [146]:
desc_df[desc_df['desc'] == '']

           isbn desc
300  0451154916
671  0670815373
681  0062770500
716  8478800336
718  0600586898
773  0394178017
807  2253004022
838  2264009306
889  0381999866

In [144]:
# for isbn in remaining_isbn:
#     desc_div = None
#     trial = 5
#     while not desc_div and trial > 0:
#         trial -= 1
#         html = get_html(isbn)
#         desc_div = html.find('div', {'id': 'description'})        
#     if desc_div:
#         if desc_div.find_all(attrs={"style" : "display:none"}):
#             print(count)
#             print(isbn)
#             desc_dict[isbn] = desc_div.find_all(attrs={"style" : "display:none"})[0].text
#             count += 1
#         elif len(desc_div.find_all('span')) == 1:
#             print(count)
#             print(isbn)
#             desc_dict[isbn] = desc_div.find_all('span')[0].text
#             count += 1

In [147]:
desc_df.to_csv('book_desc.csv', index=False)

In [159]:
books_img_df = pd.read_csv('raw_data/Books_CorrectAuthorName.csv', usecols=['ISBN', 'Image-URL-S', 'Image-URL-M','Image-URL-L'])
books_img_df = books_img_df.drop_duplicates()
books_img_df

,ISBN,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...
1,0002005018,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...
2,0060973129,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...,http://images.amazon.com/images/P/0060973129.0...
3,0374157065,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...,http://images.amazon.com/images/P/0374157065.0...
4,0393045218,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...,http://images.amazon.com/images/P/0393045218.0...
...,...,...,...,...
269677,0572011644,http://images.amazon.com/images/P/0572011644.0...,http://images.amazon.com/images/P/0572011644.0...,http://images.amazon.com/images/P/0572011644.0...
269678,1565924622,http://images.amazon.com/images/P/1565924622.0...,http://images.amazon.com/images/P/1565924622.0...,http://images.amazon.com/images/P/1565924622.0...
269689,4621027530,http://images.amazon.com/images/P/4621027530.0...,http://images.amazon.com/images/P/4621027530.0...,http://images.amazon.com/images/P/4621027530.0...
269697,0671226800,http://images.amazon.com/images/P/0671226800.0...,http://images.amazon.com/images/P/0671226800.0...,http://images.amazon.com/images/P/0671226800.0...
269706,0673733513,http://images.amazon.com/images/P/0673733513.0...,http://images.amazon.com/images/P/0673733513.0...,http://images.amazon.com/images/P/0673733513.0...

In [154]:
books_df = pd.read_csv('books.csv')
books_df

,ISBN,Book-Title,Price,Year-Of-Publication,Publisher ID
0,0195153448,Classical Mythology,75,2002,1
1,0198320264,Julius Caesar (Oxford School Shakespeare),20,2001,1
2,0192815318,Cranford (The World's Classics),25,1982,1
3,0198604025,How Not to Say What You Mean: A Dictionary of ...,80,2003,1
4,0002005018,Clara Callan,30,2001,2
...,...,...,...,...,...
887,0892967994,The Fractal Murders (Pepper Keane Mysteries),65,2004,329
888,1551668785,Final Stand,30,2002,330
889,0381999866,Magic House of Numbers.,25,1974,331
890,061312975X,This Present Darkness,30,1999,332
891,0061076031,Mary-Kate & Ashley Switching Goals (Mary-Kate ...,60,2000,333

In [165]:
desc_df = desc_df.rename(columns={'isbn': 'ISBN'})
desc_df

           ISBN                                               desc
0    0195153448  Featuring the authors' extensive, clear, and f...
1    0198320264  The Oxford School Shakespeare has become the p...
2    0192815318  `Cranford is in possession of the Amazons; all...
3    0198604025  We often use euphemisms when dealing with tabo...
4    0002005018  In a small town in Canada, Clara Callan reluct...
..          ...                                                ...
887  0892967994  "Three victims, three different states and thr...
888  1551668785  On the run from an international crime ring th...
889  0381999866
890  061312975X  A prayerful pastor and a hard-boiled reporter ...
891  0061076031  Emma Stanton is a boy magnet. Her twin sister,...

[892 rows x 2 columns]

In [175]:
final_books_df = pd.merge(pd.merge(books_df, books_img_df, on="ISBN"), desc_df, on="ISBN")
final_books_df

,ISBN,Book-Title,Price,Year-Of-Publication,Publisher ID,Image-URL-S,Image-URL-M,Image-URL-L,desc
0,0195153448,Classical Mythology,75,2002,1,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"Featuring the authors' extensive, clear, and f..."
1,0198320264,Julius Caesar (Oxford School Shakespeare),20,2001,1,http://images.amazon.com/images/P/0198320264.0...,http://images.amazon.com/images/P/0198320264.0...,http://images.amazon.com/images/P/0198320264.0...,The Oxford School Shakespeare has become the p...
2,0192815318,Cranford (The World's Classics),25,1982,1,http://images.amazon.com/images/P/0192815318.0...,http://images.amazon.com/images/P/0192815318.0...,http://images.amazon.com/images/P/0192815318.0...,`Cranford is in possession of the Amazons; all...
3,0198604025,How Not to Say What You Mean: A Dictionary of ...,80,2003,1,http://images.amazon.com/images/P/0198604025.0...,http://images.amazon.com/images/P/0198604025.0...,http://images.amazon.com/images/P/0198604025.0...,We often use euphemisms when dealing with tabo...
4,0002005018,Clara Callan,30,2001,2,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct..."
...,...,...,...,...,...,...,...,...,...
887,0892967994,The Fractal Murders (Pepper Keane Mysteries),65,2004,329,http://images.amazon.com/images/P/0892967994.0...,http://images.amazon.com/images/P/0892967994.0...,http://images.amazon.com/images/P/0892967994.0...,"""Three victims, three different states and thr..."
888,1551668785,Final Stand,30,2002,330,http://images.amazon.com/images/P/1551668785.0...,http://images.amazon.com/images/P/1551668785.0...,http://images.amazon.com/images/P/1551668785.0...,On the run from an international crime ring th...
889,0381999866,Magic House of Numbers.,25,1974,331,http://images.amazon.com/images/P/0381999866.0...,http://images.amazon.com/images/P/0381999866.0...,http://images.amazon.com/images/P/0381999866.0...,
890,061312975X,This Present Darkness,30,1999,332,http://images.amazon.com/images/P/061312975X.0...,http://images.amazon.com/images/P/061312975X.0...,http://images.amazon.com/images/P/061312975X.0...,A prayerful pastor and a hard-boiled reporter ...
891,0061076031,Mary-Kate & Ashley Switching Goals (Mary-Kate ...,60,2000,333,http://images.amazon.com/images/P/0061076031.0...,http://images.amazon.com/images/P/0061076031.0...,http://images.amazon.com/images/P/0061076031.0...,"Emma Stanton is a boy magnet. Her twin sister,..."

In [197]:
final_books_df = final_books_df.apply(lambda x: x.str.replace('"', '').str.replace('`', '').str.replace("'", "") if x.name == 'desc' else x)

In [205]:
final_books_df.rename(columns={'Book-Title': 'title', 'Price': 'price', 'Year-Of-Publication': 'published_year', 'Publisher ID': 'publisher_id', 'Image-URL-S':'image_short', 'Image-URL-M':'image_medium', 'Image-URL-L':'image_large'}, inplace=True)
final_books_df

,ISBN,title,price,published_year,publisher_id,image_short,image_medium,image_large,desc
0,0195153448,Classical Mythology,75,2002,1,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,"Featuring the authors extensive, clear, and fa..."
1,0198320264,Julius Caesar (Oxford School Shakespeare),20,2001,1,http://images.amazon.com/images/P/0198320264.0...,http://images.amazon.com/images/P/0198320264.0...,http://images.amazon.com/images/P/0198320264.0...,The Oxford School Shakespeare has become the p...
2,0192815318,Cranford (The World's Classics),25,1982,1,http://images.amazon.com/images/P/0192815318.0...,http://images.amazon.com/images/P/0192815318.0...,http://images.amazon.com/images/P/0192815318.0...,Cranford is in possession of the Amazons; all ...
3,0198604025,How Not to Say What You Mean: A Dictionary of ...,80,2003,1,http://images.amazon.com/images/P/0198604025.0...,http://images.amazon.com/images/P/0198604025.0...,http://images.amazon.com/images/P/0198604025.0...,We often use euphemisms when dealing with tabo...
4,0002005018,Clara Callan,30,2001,2,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,http://images.amazon.com/images/P/0002005018.0...,"In a small town in Canada, Clara Callan reluct..."
...,...,...,...,...,...,...,...,...,...
887,0892967994,The Fractal Murders (Pepper Keane Mysteries),65,2004,329,http://images.amazon.com/images/P/0892967994.0...,http://images.amazon.com/images/P/0892967994.0...,http://images.amazon.com/images/P/0892967994.0...,"Three victims, three different states and thre..."
888,1551668785,Final Stand,30,2002,330,http://images.amazon.com/images/P/1551668785.0...,http://images.amazon.com/images/P/1551668785.0...,http://images.amazon.com/images/P/1551668785.0...,On the run from an international crime ring th...
889,0381999866,Magic House of Numbers.,25,1974,331,http://images.amazon.com/images/P/0381999866.0...,http://images.amazon.com/images/P/0381999866.0...,http://images.amazon.com/images/P/0381999866.0...,
890,061312975X,This Present Darkness,30,1999,332,http://images.amazon.com/images/P/061312975X.0...,http://images.amazon.com/images/P/061312975X.0...,http://images.amazon.com/images/P/061312975X.0...,A prayerful pastor and a hard-boiled reporter ...
891,0061076031,Mary-Kate & Ashley Switching Goals (Mary-Kate ...,60,2000,333,http://images.amazon.com/images/P/0061076031.0...,http://images.amazon.com/images/P/0061076031.0...,http://images.amazon.com/images/P/0061076031.0...,"Emma Stanton is a boy magnet. Her twin sister,..."

In [207]:
final_books_df[['ISBN', 'title', 'desc', 'price', 'publisher_id', 'published_year', 'image_short', 'image_medium', 'image_large']].to_csv('final_books.csv', index=False)